import * as React from "react";
import Accordion from "@mui/material/Accordion";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";
import Typography from "@mui/material/Typography";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

const FAQArray = [
  {
    id: 1,
    summary: "Miner Winning Announcement",
    details: "Object: All members who successfully signed up for mining Rules: The company's node mining system draws six lucky winners every week Time: 2023.1.1~~2023.12.31 First prize (1 person): 177777 USDT Second prize (2 people): 80000 USDT Third Prize (3 people): 30000 USDT Redemption conditions: The first prize requires 18,888 USDT to participate in mining, the second prize requires 7,777 USDT to participate in mining, and the third prize requires 5,555 USDT to participate in mining.",
  },
  {
    id: 2,
    summary: "What is (USDT)?",
    details: "USDT is the full name of Decentralized Finance in English, which is DECENTRALIZED FINANCE, also know as OPEN FINANCE. USDT does not require trusted intermediaries, and the bene  ",
  },
  {
    id:3,
    summary: "How to join(USDT)Smart Mining.",
    details: "First, you need to download Binance Exchange and Crypto Wallet on your phone and complete the registration. Then buy USDT on Binance Exchange and transfer it to your wallet, you can get mining income: 3%-16% (daily income). (USDT) mining is smart so you don't need to do it yourself. You only need to receive the income generated by your wallet balance every day.",
  },
  {
    id: 4,
    summary: "Is USDT Risky?",
    details: "USDT is a blockchain-based application ecosystem. It offers a range of financial services similar to those offered by traditional banks, insurance brokers and other financial intermediaries. Similar to depositing funds into a savings account to earn interest, cryptocurrency investors can now lock up their funds or use them to provide liquidity on a range of decentralized platforms and receive interest on a regular basis.",
  },

  {
    id: 5,
    summary: "Are the funds safe?",
    details: "We use Binance, which is considered one of the safest cryptocurrency exchanges in the industry. It has layered security, which makes the chances of a successful hack or theft extremely low. Additionally, it covers all digital and fiat deposit insurance schemes stored in their accounts. Some of these security features are enforced by users to protect their accounts from unauthorized access and delay any unauthorized transactions or transfers. And there will be 12 mnemonics when you register and log in, as long as you don't reveal your private key, you are the only person in the world who can trade and control it.",
  },

  {
    id: 6,
    summary: "How to quit?",
    details: "We use Binance, which is considered one of the safest cryptocurrency exchanges in the industry. It has layered security, which makes the chances of a successful hack or theft extremely low. Additionally, it covers all digital and fiat deposit insurance schemes stored in their accounts. Some of these security features are enforced by users to protect their accounts from unauthorized access and delay any unauthorized transactions or transfers. And there will be 12 mnemonics when you register and log in, as long as you don't reveal your private key, you are the only person in the world who can trade and control it.",
  },

  {
    id: 7,
    summary: "Why do we need to pay miners to cash out profits?",
    details: "Because in the process of participating in mining, the customer only counts the name, and the miner's fee has been paid by the miners. The revenue generated is actually in a contract pool, and only the miner's fee can be exchanged for revenue, which only needs to be paid once.",
  },

  {
    id: 8,
    summary: "How do I participate?",
    details: "1. The wallet is on the chain, and the wallet comes with a Dapp browser 2. Connect BEP20 to USDT and deposit into your wallet 3. Enter the official website through the wallet browser 4. Your wallet must have more than 10USDT BEP20 as miner fee to participate in this project.",
  },

  {
    id: 9,
    summary: "What is USDT Liquidity Mining?",
    details: "Liquidity mining is a type of Defi decentralized finance. It does not need to buy graphics cards, contribute computing power, or pay expensive electricity bills, but obtain income by providing funds and liquidity. Especially recently, the currency price has fluctuated greatly. For some staunch currency holders, liquidity mining is a way to obtain income and accumulate more cryptocurrencies without trading.",
  },
];
export default function FAQ() {
  const [expanded, setExpanded] = React.useState<string | false>(false);

  const handleChange =
    (panel: string) => (event: React.SyntheticEvent, isExpanded: boolean) => {
      setExpanded(isExpanded ? panel : false);
    };

  return (
    <div className="mx-3 p-4 bg-[#212244] flex flex-col space-y-4 justify-between rounded-xl">
      <h1 className="font-semibold text-[20px] mb-4">Help Center</h1>
      {FAQArray.map((faq) => (
        <CustomAccordion
          key={faq.id}
          {...faq}
          expanded={expanded}
          handleChange={handleChange}
        />
      ))}
    </div>
  );
}

type CustomAccordionProp = {
  id: number;
  summary: string;
  details: string;
  expanded: any;
  handleChange: any;
};
const CustomAccordion = ({
  summary,
  details,
  id,
  expanded,
  handleChange,
}: CustomAccordionProp) => {
  return (
    <Accordion
      expanded={expanded === `panel${id}`}
      onChange={handleChange(`panel${id}`)}
      elevation={0}
      sx={{ background: "#2C2C52", color: "#fff", borderRadius: "6px" }}
    >
      <AccordionSummary
        expandIcon={
          <ExpandMoreIcon className="text-[#2C2C52] h-2 w-2 rounded-full bg-white" />
        }
        aria-controls="panel1bh-content"
        id={`panel${id}bh-header`}
      >
        <p className="text-[18px] font-semibold">{summary}</p>
      </AccordionSummary>
      <AccordionDetails className="bg-[#2C2C52]" sx={{ borderRadius: "6px" }}>
        <p className="text-[14px]">{details}</p>
      </AccordionDetails>
    </Accordion>
  );
};
